
lane :pre do
	gradle(task: "assembleDebug")
	gradle(task: "assembleAndroidTest")
end


lane :flavorScreenshots do |options|
	screengrab(output_directory: "fastlane/metadata/android/" + options[:flavor], app_package_name: "org.stepik.android.adaptive." + options[:flavor], app_apk_path: "app/build/outputs/apk/app-" + options[:flavor] + "-debug.apk", tests_apk_path: "app/build/outputs/apk/app-" + options[:flavor] + "-debug-androidTest.apk")
end


lane :screenshots do
	pre
	flavorScreenshots(flavor: "pdd")
	flavorScreenshots(flavor: "gmat1906")
	flavorScreenshots(flavor: "gmat3067")
	flavorScreenshots(flavor: "toefl3124")
	flavorScreenshots(flavor: "toefl3149")
	flavorScreenshots(flavor: "toefl3150")	
end
