name: Feature Branch CI

#on:
#  push:
#    branches:
#      - 'feature/*'

jobs:
  ci:
    name: Run ktlint
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Fix secrets
        run: |
          mv buildsystem/secret.gradle buildsystem/secret.gradle_
          cat <<EOF >buildsystem/secret.gradle
          ext {
              keystore = ""
              keystorePass = ""
              oldAlias = ""
              oldAliasPass = ""
              alias = ""
              aliasPass = ""
              debugKeystore = ""
              debugKeystorePass = ""
              debugAlias = ""
              debugAliasPass = ""
          }
          EOF

      - name: Run ktlint
        run: bash ./gradlew ktlint --stacktrace